version: '3'
services:
  frontend:
    build:
      context: ./ecommerce-ui
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
     - "3001:80" 
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./ecomerce-server
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
